---
- name: Enforce s3 versioning
  hosts: localhost

  tasks:
    - name: List s3 buckets in my account
      amazon.aws.s3_bucket_info:
      register: result

    - name: Display results on console
      ansible.builtin.debug:
        var: result

    - name: Enable versioning on s3 buckets
      amazon.aws.s3_bucket:
        name: "{{ item.name }}"
        versioning: yes
      loop: "{{ result.buckets }}"
