---
- hosts: localhost
  connection: local
  tasks: 
    - name: create EC2 instances
      amazon.aws.ec2_instance:
        name: "{{item.name}}"
        key_name: "Ansible-11Jan"
        # vpc_subnet_id: subnet-5ca1ab1e
        instance_type: "t2.micro"
        security_group: default
        region: us-east-1
        aws_access_key: "{{ aws_access_key }}" # from vault as defined
        aws_secret_key: "{{ aws_secret_key }}" # from vault as defined
        network_interfaces:
          - assign_public_ip: true
        image_id: "{{item.image}}"
        tags:
          Environment: Testing
      loop:
        - { image: "ami-0453ec754f44f9a4a", name: "managed-node-1" }
        - { image: "ami-0866a3c8686eaeeba", name: "managed-node-2" }
        - { image: "ami-0866a3c8686eaeeba", name: "managed-node-3" }


